version: "3"

services:
  php:
    build: ./
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    links:
      - mysql:mysql
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test1234
      - MYSQL_DATABASE=blog