version: "3"

services:
  php:
    build: ./
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    ports:
      - 80:80